CREATE TABLE USUARIO(
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(40)		NOT NULL,
	DATAHORACRIACAO	DATETIME			NOT NULL,
	PRIMARY KEY(IDUSUARIO))
GO

CREATE TABLE CATEGORIA(
	IDCATEGORIA		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(IDCATEGORIA),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO))
GO

CREATE TABLE CONTA(
	IDCONTA			UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	DATA			DATE				NOT NULL,
	VALOR			DECIMAL(18,2)		NOT NULL,
	TIPO			INTEGER				NOT NULL,
	OBSERVACOES		NVARCHAR(500)		NOT NULL,
	IDCATEGORIA		UNIQUEIDENTIFIER	NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(IDCONTA),
	FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO))
GO